In [1]:
#from NeuralNetworks import *
import numpy as np
from network import Network

In [2]:
X = np.random.rand(1000,1)
Y = 2*X + 1

In [13]:
model = Network(
    layerSizes=[1,16,1],
    activations=["relu",""],
    lossName="mse"
)

model.Train(X, Y, learningRate=0.01, epochs=200, batchSize=32)

Epoch 1:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 2:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 3:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 4:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 5:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 6:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 7:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 8:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 9:    Loss=0.1359,  Test R^2= -1134.66%
Epoch 10:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 11:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 12:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 13:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 14:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 15:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 16:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 17:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 18:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 19:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 20:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 21:   Loss=0.1359,  Test R^2= -1134.66%
Epoch 22:   Loss=0.1359,  Test R^2

In [12]:
print(X[:5].reshape(1,-1))
print(Y[:5].reshape(1,-1))
print(model.Forward(X[:5]).reshape(1,-1))

[[0.87226484 0.25226939 0.08754553 0.84262777 0.84681274]]
[[2.74452969 1.50453878 1.17509105 2.68525553 2.69362549]]
[[0. 0. 0. 0. 0.]]


In [4]:
model.Summary()

Model Summary
Layer      Input → Output       Activation      Params    
--------------------------------------------------
0          1→16              ReLU            32        
1          16→1               ReLU            17        
--------------------------------------------------
Total parameters: 49


In [5]:
model.PlotLossAccuracy

<bound method Network.PlotLossAccuracy of <network.Network object at 0x0000013EFED916A0>>